#!/bin/bash

rm -f *.so test

gcc -g3 -m64 -fPIC -shared -o libtest1.so libtest1.c
gcc -g3 -m64 -fPIC -shared -o libtest2.so libtest2.c

gcc -g3 -m64 -L$PWD -o test test.c elf_hook.c -ltest1 -ltest2 -ldl
